### ISSUE TITLE
Config examples not working

### ISSUE THREAD

**Issue by gianfrdp** [mrtncls/mqtt-translator#1]
Hello,
I'm trying to create a config file to test mqtt-translator, but fails.
I tried last example
```
source:
  id: MQTT-Translator-Source
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
    - 1235332/#
  publish:
    cooldown: 2
    convert:
target:
  id: MQTT-Translator-Target
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
  publish:
    cooldown: 2
    convert:
      - topic:
        - from: '1235332'.
          to: 'temp_sensor'
```
running program returns errors
```
python3.7 -m mqtt_translator -c config.yaml

2021-06-08 17:26:52,461 INFO main: Loading setup...
__main__.py:22: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "__main__.py", line 33, in <module>
    main()
  File "__main__.py", line 24, in main
    bridge = Bridge(config)
  File "bridge.py", line 15, in __init__
    sourceClient, sourceConfig['topics'], sourcePublishConfig['cooldown'], sourcePublishConfig['convert'])
  File "bridge_client.py", line 15, in __init__
    self._convertor = MessageConvertor(convert_config)
  File "message_convertor.py", line 10, in __init__
    for configLine in config:
TypeError: 'NoneType' object is not iterable
```
Can I have a working example, please?
I have to implement a conveter from one topic and paylod to another,

Thanks

**Comment by mrtncls** [comment]
There is a dot behind the string in the last from. Think it should be only a string.
Can you try without it?

**Comment by gianfrdp** [comment]
Hello,
I remove dirty character, but nothing changed
```
gianfranco@t3500:~/mqtt-translator $ cat config.yaml
source:
  id: MQTT-Translator-Source
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
    - 1235332/#
  publish:
    cooldown: 2
    convert:

target:
  id: MQTT-Translator-Target
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
  publish:
    cooldown: 2
    convert:
      - topic:
        - from: '1235332'
          to: 'temp_sensor'

gianfranco@t3500:~/mqtt-translator $ python3.7 -m mqtt_translator -c config.yaml
2021-06-09 14:47:50,449 INFO main: Loading setup...
~/mqtt-translator/mqtt_translator/__main__.py:22: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/mqtt-translator/mqtt_translator/__main__.py", line 33, in <module>
    main()
  File "~/mqtt-translator/mqtt_translator/__main__.py", line 24, in main
    bridge = Bridge(config)
  File "~/mqtt-translator/mqtt_translator/bridge.py", line 15, in __init__
    sourceClient, sourceConfig['topics'], sourcePublishConfig['cooldown'], sourcePublishConfig['convert'])
  File "~/mqtt-translator/mqtt_translator/bridge_client.py", line 15, in __init__
    self._convertor = MessageConvertor(convert_config)
  File "~/mqtt-translator/mqtt_translator/translator/message_convertor.py", line 10, in __init__
    for configLine in config:
TypeError: 'NoneType' object is not iterable
```
It seems that program doesn't accept void "convert" section in source
Thanks.

**Comment by mrtncls** [comment]
The example is bad.
There should at least be one convertor for now.

Please try this config:

```yaml
source:
  id: MQTT-Translator-Source
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
    - 1235332/#
  publish:
    cooldown: 2
    convert:
      - topic:
        - from: '1235332'
          to: 'temp_sensor'

target:
  id: MQTT-Translator-Target
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
  publish:
    cooldown: 2
    convert:
      - topic:
        - from: '1235332'
          to: 'temp_sensor'
```

**Comment by gianfrdp** [comment]
It seems I can go a little ahead with your config, but I still have error:
```Shell
gianfranco@t3500:~/mqtt-translator (master M) [!1] $ python3.7 -m mqtt_translator -c config.yaml
2021-06-10 14:35:08,157 INFO main: Loading setup...
~/mqtt-translator/mqtt_translator/__main__.py:22: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
2021-06-10 14:35:08,164 INFO __init__: Bridge created
2021-06-10 14:35:08,164 INFO main: Setup completed
2021-06-10 14:35:09,165 INFO loop: b'MQTT-Translator-Source' connecting...
2021-06-10 14:35:10,169 INFO loop: b'MQTT-Translator-Target' connecting...
2021-06-10 14:35:10,170 INFO on_connect: MQTT-Translator-Source connected
2021-06-10 14:35:10,171 DEBUG on_connect: MQTT-Translator-Source subscribed to salasensors/#
2021-06-10 14:35:10,171 INFO on_connect: MQTT-Translator-Target connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/mqtt-translator/mqtt_translator/__main__.py", line 33, in <module>
    main()
  File "~/mqtt-translator/mqtt_translator/__main__.py", line 29, in main
    bridge.loop()
  File "~/mqtt-translator/mqtt_translator/bridge.py", line 32, in loop
    self._target.loop()
  File "~/mqtt-translator/mqtt_translator/bridge_client.py", line 49, in loop
    self.client.loop()
  File "~/mqtt-translator/mqtt_translator/paho_mqtt_client.py", line 17, in loop
    loopResult = super().loop(0.01, 1)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3030, in _handle_connack
    self, self._userdata, flags_dict, result)
  File "~/mqtt-translator/mqtt_translator/bridge_client.py", line 24, in on_connect
    for topic in self.topics:
TypeError: 'NoneType' object is not iterable
```
I have an error  on target section, when program tries to loop on topics, so seems that also "topics" is mandatory on target.
I can subscribe to a topic `salasensors/tele/SENSOR` with a client, I can see messages:
```Shell
gianfranco@t3500:~ [!1] $ mosquitto_sub  -t 'salasensors/tele/SENSOR' -d -i "test_sub"
Client test_sub sending CONNECT
Client test_sub received CONNACK (0)
Client test_sub sending SUBSCRIBE (Mid: 1, Topic: salasensors/tele/SENSOR, QoS: 0, Options: 0x00)
Client test_sub received SUBACK
Subscribed (mid: 1): 0
Client test_sub received PUBLISH (d0, q0, r0, m0, 'salasensors/tele/SENSOR', ... (107 bytes))
{"Time":"2021-06-10T14:25:36","AM2301":{"Temperature":24.6,"Humidity":48.9,"DewPoint":13.1},"TempUnit":"C"}
```
or `salasensors/#`
```Shell
gianfranco@t3500:~ $ mosquitto_sub -t "salasensors/#" -d -i "test_sub2" --pretty
Client test_sub2 sending CONNECT
Client test_sub2 received CONNACK (0)
Client test_sub2 sending SUBSCRIBE (Mid: 1, Topic: salasensors/#, QoS: 0, Options: 0x00)
Client test_sub2 received SUBACK
Subscribed (mid: 1): 0
Client test_sub2 received PUBLISH (d0, q0, r1, m0, 'salasensors/tele/LWT', ... (6 bytes))
Online
```
but if I run your program with modified config:
 ```
source:
  id: MQTT-Translator-Source
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
    - salasensors/#
  publish:
    cooldown: 2
    convert:
      - topic:
        - from: 'salasensors/tele/SENSOR'
          to: 'domoticz/in'

target:
  id: MQTT-Translator-Target
  host: 127.0.0.1
  port: 1883
  keepalive_interval: 60
  topics:
  publish:
    cooldown: 2
    convert:
      - topic:
        - from: 'salasensors/tele/SENSOR'
          to: 'domoticz/in'
```
I have same error.
Do you have a working config.yaml example?

**Comment by mrtncls** [comment]
Seems I didn't made those optional. In my usecase, I had to map in both directions.
But you can just add a non existing topic. It won't do anything untill something is published to that topic.
I'll have a look on your PR.
